### ISSUE TITLE
Gauge Cards keep dropping to zero

### ISSUE THREAD

**Issue by rjenx** [ownbee/bootstrap-grid-card#10]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser
- **Version:** 2023.4.6
- **Last working release (if known):** unknown
- **Browser and Operating System:** Brave, Windows

I first noticed this issue with the weather card which seems to flicker frequently, ignored the issue because its of minor importance. 
However experimenting with new grid views I built a prototype with a grid of gauges showing temperature and humidity sensors. 
The gauges will frequently drop to zero, then bounce back to the correct value. This happens with some regularity, typically 1 - 2 seconds, then a brief respite for 4 - 5 seconds then back to 1 - 2 seconds. 

I assumed it was something to do with screen refresh when I saw the problem with weather card. But I cannot find any settings which may influence this behaviour. 

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**

https://user-images.githubusercontent.com/64302977/234057835-3a4df836-82e7-460b-8fc7-e9f3ccf296bc.mp4

**Comment by ownbee** [comment]
Just released a new version that might remove your problem.

**Comment by rjenx** [comment]
> Just released a new version that might remove your problem.

Tried the new version, it broke my UI. All I had was the 1st row missing a button custom: auto-entities.  All rows after the 1st row are missing. I have returned my installation to version 0.1.3 and all fixed. Is there anything I can provide that might help you understand what went wrong? 

I Emptied Cache and Hard Reloaded from developer tools, rebooted HA with no effect.

**Comment by ownbee** [comment]
Hmm, my test setup includes nested rows and column and works fine there. Does the developer console in your browser say anything interesting?

If there is nothing there, can you post your yaml configuration?

**Comment by rjenx** [comment]
Hi thanks for your assistance, I think the problem is with the simple thermostat and grid card combination. 
This is the error that appears in the dev console. 
```
mple-thermostat.js?hacstag=158654878250:292 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'attributes')
    at simple-thermostat.js?hacstag=158654878250:292:19947
    at set hass [as hass] (simple-thermostat.js?hacstag=158654878250:292:20167)
    at tt.build_card (bootstrap-grid-card.js?hacstag=334448958012:20:1777)
    at bootstrap-grid-card.js?hacstag=334448958012:20:932
    at Array.forEach (<anonymous>)
    at tt.build_row (bootstrap-grid-card.js?hacstag=334448958012:20:482)
    at bootstrap-grid-card.js?hacstag=334448958012:20:876
    at Array.forEach (<anonymous>)
    at tt.build_row (bootstrap-grid-card.js?hacstag=334448958012:20:482)
    at tt.build_configured_cards (bootstrap-grid-card.js?hacstag=334448958012:20:407)
```

I am still looking at the issue with my main page when upgrading to v0.2

**Comment by rjenx** [comment]
I will close this, it looks like a number of cards used on the page are not being found since the last updates. Unsure why so will continue to investigate the cause. But until I eliminate these issues I cannot be sure what the cause is of the problem with my UI.

**Comment by rjenx** [comment]
Are you seeing any problems with the grid card popup through the android app?

**Comment by ownbee** [comment]
> Are you seeing any problems with the grid card popup through the android app?

No, works fine for me both on desktop, mobile and tablet. Tested on: Chrome browser, Brave browser, Firefox browser and Android App.

May I suggest you press F12 (developer tools) and check the "console" log. Verify that you see  "BOOTSTRAP-GRID-CARD Version 0.2.0" is printed there, since that means the card was loaded correctly. Then fallback to a very simple lovelace configuration with only built in cards that are know to work (e.g. button card or gauge) and make sure no other custom cards are loaded (remove them from resources). Then add back cards and configuration one step at a time and see were it breaks.
 
I only have a very small portion of custom cards. So I don't know if there are custom cards that can break the grid. Some custom cards are altering stuff on global scope which could affect this grid card implicitly.

**Comment by rjenx** [comment]
I identified a problem with the nabu casa integration which for reasons i dont understand retained the previous version of my UI. Deleting and reinstalling both the integration and the app resolved the issue. Thanks for your help and quick responses. Your grid card is the best UI feature available.

**Comment by ownbee** [comment]
Thanks, I am glad you solved the problem.
