### ISSUE TITLE
Simply not working

### ISSUE THREAD

**Issue by NVader2000** [ownbee/bootstrap-grid-card#4]
I installed the bootstrap-grid card per the instructions, but nothing seems to be working. Not sure I understand how your card works and what I should be doing. Sorry, your instructions are not noticeably clear.  I am sure users with advanced knowledge or more experience will work right through this with no issue, but not everyone is as knowledgeable and will need some dumped down instructions with more clarification.

Yes, I did clear cache and reload the page.

Please advise and thank you

**Comment by ownbee** [comment]
How did you install it? Via HACS or manually? If first, did you add the card into resources described in HACS instructions?

Press f-12 while in browser and then "console" and you can look for ths card to see if it is proberly loaded.

**Comment by ownbee** [comment]
I've looked over the documentation and done some minor clarifications. Please open a new issue if you still have problems. Closing this issue.
