### ISSUE TITLE
Update Bootstrap

### ISSUE THREAD

**Issue by reypm** [ownbee/bootstrap-grid-card#7]
Can the Bootstrap version be updated to the latest 5.3.x?

**Comment by ownbee** [comment]
sure, my ambition is to keep it updated, i have just not found a great need for it yet. out of curiosity, what do you miss in the existing version?

**Comment by ownbee** [comment]
5.3.x seem to be alpha. I will not upgrade to it until it is properly released unless there are a very good reason for it.

**Comment by reypm** [comment]
> what do you miss in the existing version?
Nothing to be honest. I'm just one of those who likes to keep on the cutting-edge technologies side 😄 and somehow falling behind on the Bootstrap version, sometimes, gives the impression that the developer abandons the development.

> 5.3.x seem to be alpha
it is an alpha and I did not notice that you are right, let's wait on a stable version. I am gonna close this for now, thanks for your support.
